### ISSUE TITLE
DataTables won't search any column that shows data from a linked table

### ISSUE THREAD

**Issue by nathanhollows** [wisend/avaunt#18]
The current initialisation of datatables doesn't allow for data pulled from related models to be searched.

Example: On the customers page it is not possible to search for "Dead" quotes in the search input.

**Comment by nathanhollows** [comment]
Issue originally reported here: [m1ome/phalcon-datatables/issues/17](https://github.com/m1ome/phalcon-datatables/issues/17)

**Comment by stefanchiriac** [comment]
I just wanted to let you know that I fixed this issue. https://github.com/magnxpyr/phalcon-datatables
